dist: bionic
sudo: required
language: sh
addons:
  apt:
    update: true
    packages:
    - xvfb
    - x11-apps
    - imagemagick
    - ffmpeg
  homebrew:
    update: true
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain make
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        # taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        # export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac  
    bash -x setup.sh
script:
- |-
    pkg-config --cflags --libs gtk+-3.0 
    case $TRAVIS_OS_NAME in
    linux)
      make
      ;;
    osx)
      pkg-config --variable pc_path pkg-config
      find /usr -name gtk+-3.0.pc
      brew ls -v gtk+-3
      PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/ make
      ;;
    windows)
      # MSYS
      $msys2 bash -x build.sh
      ;;
    esac
os:
  - linux
  - osx
  - windows
